### ISSUE TITLE
A typing error in setup_refs.py

### ISSUE THREAD

**Issue by AssiaSaltykova** [phe-bioinformatics/kmerid#1]
The setup_refs.py script does not work for larger reference sets, giving the following output:

49 kmer lists made or found.
found similarity matrix for reference group neisseria, skipping creation ...
Created sim mat file: config/neisseria_simmat.tsv
Traceback (most recent call last):
  File "setup_refs.py", line 286, in <module>
    main()
  File "setup_refs.py", line 143, in main
    oConf.set('%s_refsets' % oArgs.name, str(k), d40Cen[k])
  File "/home/assia/miniconda2/lib/python2.7/ConfigParser.py", line 396, in set
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'neisseria_refsets'

Mb on line 143, '%s_refsets' should be '%s_refset' or someting like that

**Comment by ulfschaefer** [comment]
Hi there. You're correct. That's what the line should be. Sorry about that. I fixed it in commit b814e4c6488981d66d61ad3481ad773a2dad55c0. Please let me know if it now works for you. It seems to for me. Thanks.

**Comment by AssiaSaltykova** [comment]
Yes indeed, it works for me too. Thanks!
