### ISSUE TITLE
Can I use one NCBI NC genome as the reference

### ISSUE THREAD

**Issue by yingeddi2008** [phe-bioinformatics/kmerid#2]
Hi kmerid engineer,

I read about your software in a recent paper, where they mentioned that it is a faster way of calculating inter-genus strain level distance. I am very curious to try. 

I downloaded and installed the software following the instructions, however, when I want to process the reference genome, error message occurs:

```
$ python setup_refs.py -f /N/dc2/scratch/dongq/IUMP/kmerid/ref/ -n 'Haemophilus_influenzae' -c config/config.cnf 
1 sequence files found.
/N/dc2/scratch/dongq/IUMP/kmerid/ref/NC_014922.1_kmers.txt - kmer list found. skipping creation.
1 kmer lists made or found.
creating similarity matrix for reference group haemophilus_influenzae ...
Created sim mat file: config/haemophilus_influenzae_simmat.tsv
Traceback (most recent call last):
  File "setup_refs.py", line 286, in <module>
    main()
  File "setup_refs.py", line 125, in main
    d3Cl = cluster_group(sSimMatFile, 3)
  File "setup_refs.py", line 234, in cluster_group
    linkage_matrix = linkage(squareform(a), method='average')
  File "/N/soft/rhel7/python/2.7.13a/lib/python2.7/site-packages/scipy-1.0.0.dev0+2b7ce39-py2.7-linux-x86_64.egg/scipy/cluster/hierarchy.py", line 678, in linkage
    n = int(distance.num_obs_y(y))
  File "/N/soft/rhel7/python/2.7.13a/lib/python2.7/site-packages/scipy-1.0.0.dev0+2b7ce39-py2.7-linux-x86_64.egg/scipy/spatial/distance.py", line 1812, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.
```

Would it be possible because there is only one sequence in the fasta file under that directory? If not, what are my options to proceed?

Thanks, 

Eddi

**Comment by ulfschaefer** [comment]
Hi Eddi

This is indeed because you have only one reference genome in your folder. The simplest solution is to add a second reference genome from H. influenzae into the folder.

KmerID will tell you the distance between a genome sequenced with short read data and a reference genome in fasta format. It considers each fasta file in the ref folder to contain one reference genome. It does not matter how many sequences the fasta file contains.

Hope this helps
Ulf

**Comment by yingeddi2008** [comment]
Thank you!
